# Generated by Django 2.1.7 on 2019-03-16 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('old_weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('new_weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
